### ISSUE TITLE
[Bug]: Something went wrong

### ISSUE THREAD

**Issue by chokiproai** [danny-avila/LibreChat#1011]
### What happened?

i used full cookies but only asked once and next time got error and i followed this https://github.com/danny-avila/LibreChat/issues/727#issuecomment-1659407747 ,but still not working

### Steps to Reproduce

Normal conversation.

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/128912789/caa14a45-402a-4c6b-8620-e7d3f64aba7f)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
To some people, it works even after the second message, while for others it doesn't. Since no API key is being used, it's difficult to understand the problem. I also have the same issue and if I want to use Bing, I select Sydney (which works even after the second message). Take a look [here](https://discord.com/channels/1086345563026489514/1143941308684177429)

**Comment by hayschan** [comment]
> To some people, it works even after the second message, while for others it doesn't. Since no API key is being used, it's difficult to understand the problem. I also have the same issue and if I want to use Bing, I select Sydney (which works even after the second message). Take a look [here](https://discord.com/channels/1086345563026489514/1143941308684177429)

Thanks for the tips. It helped me a lot!
