### ISSUE TITLE
Request to run local LLMs instead of paid API 

### ISSUE THREAD

**Issue by jabo38** [danny-avila/LibreChat#1131]
### What features would you like to see added?

There are free open-source databases you can run at home now and they will only get better. 

Installing has been made easy via sites like https://ollama.ai/

Please add support to connect to local database via Ollama.

### More details

There is a great need for people be be able to run their own open source LLM at home. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can try using a project like [litellm](https://github.com/BerriAI/litellm) which can connect to ollama, and be used as a backend for Open Source models. I will test it soon and then write a guide.

**Comment by jabo38** [comment]
That would be great. Thanks!

**Comment by bsu3338** [comment]
If it helps, LiteLLM mentions running LibreChat and ollama in the below page

[LiteLLM Documentation - Proxy Server](https://docs.litellm.ai/docs/proxy_server)

**Comment by nightpool** [comment]
I think it's pretty misleading to call this project "LibreChat" when it's relying on proprietary, paid APIs

**Comment by danny-avila** [comment]
> I think it's pretty misleading to call this project "LibreChat" when it's relying on proprietary, paid APIs

Libre in software means to have "very few limitations on distribution or the right to access the source code to create improved versions." This project is completely open-source, with the least limited license for use, and utilizes open-source solutions and philosophies, to improve upon its origin for those who build and use it. 

The fact that this project has been downloaded over 650,000 times from github containers, not including non-container downloads, without transacting a single dollar for this, lays claim to the term `Libre` even in its inherent meaning.

To be clear, it's not relying on proprietary, paid APIs as you said, rather building mainly on a framework that OpenAI has set as the industry standard for interacting with LLMs remotely. LibreChat can utilize countless other open-source solutions to use local large language models following this framework, which is why it's useful to have a standard. This is not limited to LiteLLM, but also to many other API services that integrate local LLM solutions.

@nightpool This project lays more claim to being open-source than even [Meta's LLama models](https://spectrum.ieee.org/open-source-llm-not-open), and frankly your comment undermines the open-source efforts to provide it freely.

**Comment by danny-avila** [comment]
I'm going to close this in favor of https://github.com/danny-avila/LibreChat/issues/1344

It's not like you can't run local LLMs using other tools in combination with LibreChat.

Right now, this isn't a huge priority but it's planned to have a dedicated 'reverse proxy' endpoint to serve any alternative endpoint need, provided the OpenAI spec is followed, which even Mistral API follows.
