### ISSUE TITLE
Enhancement: Incorporate Text to Speech Models

### ISSUE THREAD

**Issue by jantznick** [danny-avila/LibreChat#1198]
### Contact Details

thenickjantz@gmail.com

### What features would you like to see added?

Incorporate the text to speech models to turn responses into an audio stream/file that can be played in the browser.

### More details

The endpoint is pretty simple. I'd be happy to implement it just curious on how it should best be done or implemented into the current UI.

https://platform.openai.com/docs/guides/text-to-speech

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
there is an open PR that i will revisit sometime, but you can take a look and see how it was implemented without openai's TTS

https://github.com/danny-avila/LibreChat/pull/756



Note: the UI is being replaced.

This PR is not too stale since it uses new components mostly, only 11 files touched, and the old ones have easier to work with counterparts

(discord links)
[Instructions on how to access the new UI (on latest commit to main branch)](https://discord.com/channels/1086345563026489514/1086345563026489517/1174750805295911012)

[General discussion of this UI change and bugs reported here](https://discord.com/channels/1086345563026489514/1174761417199599676)
