### ISSUE TITLE
Enhancement: More information about plugins

### ISSUE THREAD

**Issue by jonas-w** [danny-avila/LibreChat#1242]
### What features would you like to see added?

When browsing the plugin store, you only get a short description and an icon.

There is no information, if this plugin is "built-in", if it got sourced from somewhere else, if it makes API calls to somewhere else, no developer information, no privacy policy, nothing.

For example, the Web Search plugin.
I search through this repo and couldn't find any reference to where this Plugin is the defined, where it gets 'sourced' from and so on.
So I took a look at the /api/plguins request and saw that the icon for this plugin is loaded from https://websearch.plugsugar.com/. After this, I searched for this link in the repo and only then found it. https://github.com/danny-avila/LibreChat/blob/main/api/app/clients/tools/.well-known/web_search.json

There is at least some contact information and a website for it, so the data would be there.

### More details

What I really like on chat.openai.com is, that if a GPT makes a web request, it will ask the user first, if it should be allowed to make a web request to "example.com". And then there are the buttons, allow, always allow or deny. And it **needs** to have a privacy policy attached to be published.
![image](https://github.com/danny-avila/LibreChat/assets/32615971/3862d522-e898-4851-94cd-cee62510f04a)

But this could be another feature request

### Which components are impacted by your request?

UI, Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> if a GPT makes a web request, it will ask the user first, if it should be allowed to make a web request to "example.com".

This is a new behavior, and the current plugin system mimics the old way where this was never done. 

I was unaware you could toggle the asking on/off for GPTs and I'll have to keep that in mind.

GPTs are coming to LibreChat. That said, I may just add these warnings to the plugin store descriptions, since the plugins system will be somewhat be deprecated in favor of GPTs and don't want to invest a lot of time adding the complexity here. I may revisit it later for non-OpenAI LLMs

I'll keep this in mind to mimic the behavior for GPTs as much as possible.

**Comment by danny-avila** [comment]
> @danny-avila sorry to hijack this issue, but I just saw, that the plugins mode always uses 'gpt-4' even though I have selected gpt-4 turbo (gpt-4-1106-preview) in the dropdown, and I also don't have gpt-4 in the PLUGIN_MODELS. Any idea why that is?

ah yes I know why, a bit of an oversight. Going to fix this now and write some unit tests for it
