### ISSUE TITLE
[Bug]: Mobile View not optimal

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1436]
### What happened?

The "free" space in the center of the "new chat" UI is too high. The input field is below the viewport, not visible without scrolling. 

### Steps to Reproduce

1. Open `/c/new` on an iPhone (or Android, but there it looks better for me although not correct also)

The screenshots are from Chrome on an iPhone 15 Pro Max (1290x2796), and a Samsung Galaxy A22 (720x1600).

### What browsers are you seeing the problem on?

Mobile (iOS), Mobile (Android)

### Screenshots

Chrome on iOS (same on Safari):
![IMG_8788](https://github.com/danny-avila/LibreChat/assets/3326929/a1c3b387-fdb1-467b-b8a0-ec33770c4478)
![IMG_8789](https://github.com/danny-avila/LibreChat/assets/3326929/398b2450-a5cb-4c98-8001-38ca7076cd8d)

Chrome on Android looks better:
![aea25f63-f132-4fe3-868e-faec14e9db41](https://github.com/danny-avila/LibreChat/assets/3326929/4913453b-b3c0-48fb-b280-d3febab53ad2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SailFlorve** [comment]
Same on Edge Mobile.

**Comment by danny-avila** [comment]
Will look into it. Input is already focused so will have to look into it

**Comment by nyamadan** [comment]
I think if we use [h-dvh](https://tailwindcss.com/docs/height#dynamic-viewport-height) instead of h-screen, the input box will not be hidden.

![h-screen](https://github.com/danny-avila/LibreChat/assets/304238/2b729a53-c0f6-4ba4-81cc-df82ce407a1b)
![h-dvh](https://github.com/danny-avila/LibreChat/assets/304238/72a36012-6360-47d4-a80d-b468ac1d662f)

Below is the patch.
https://github.com/nyamadan/LibreChat/commit/0acacbd665e384601492e2ab6ff45ac548de3750

Could I create a PullRequest?

**Comment by danny-avila** [comment]
> Could I create a PullRequest?

Absolutely, this repo welcomes PRs. I see you made one and will review it soon
