### ISSUE TITLE
Enhancement: Dynamic Context Token Size for OpenRouter LLM

### ISSUE THREAD

**Issue by dannykorpan** [danny-avila/LibreChat#1698]
### What is your question?

Hi,

I'm testing codellama/codellama-70b-instruct LLM from OpenRouter. It's limited to a context length of 2,048 tokens. But it's capable for unlimited context length.

My questions are:
1. How do I set longer context length. e.g. 128k.
2. How do I disable the [middle-out transform]([middle-out](https://openrouter.ai/docs#transforms) transform)?

### More Details

Link to LLM on OpenRouter: https://openrouter.ai/models/codellama/codellama-70b-instruct

Thank you for your help in advance,
Danny

### Screenshots

<img width="605" alt="grafik" src="https://github.com/danny-avila/LibreChat/assets/8004507/f33e24f9-bfe3-4910-92af-dc658cf1b4d2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can't, but OpenRouter does return context token size when fetching models. I've been thinking on how to use this and will have an update on this soon

**Comment by danny-avila** [comment]
> <img width="605" alt="301499842-f33e24f9-bfe3-4910-92af-dc658cf1b4d2" src="https://github.com/danny-avila/LibreChat/assets/110412045/3c9d8eb2-a0b1-4b96-983e-318d7983cbb3">

So I couldn't find a way to "disable" middle-out in their docs, but if you do "infinite" context, then it implies middle-out is 'activated', so my assumption is that "disabling" is abiding to the 2048 context of that model.

My upcoming update will use their rates, which may not be satisfactory to you for this particular model since it only has 2048 context. I think this is fine though, since they are discarding your tokens anyway (it just won't appear that way)

**Comment by danny-avila** [comment]
LibreChat is already doing what OpenRouter would do if you exceed the context though.

> it's capable for unlimited context length.

this is not really true. They just discard your tokens  with the “middle-out” strategy if you go over. Disabling it would run you into context length error. LibreChat discards tokens that would exceed the context, starting from the tail end of the conversation
