### ISSUE TITLE
Enhancement: Shareable Presets

### ISSUE THREAD

**Issue by unitedrule** [danny-avila/LibreChat#1956]
### What features would you like to see added?

Presets can be configured to be either private or public.

### More details

Private mode is similar to the current implementation of Librechat.
Public mode displays the presets to all other registered users, preferably in a separate section so they don't get mixed up with the private presets of each use.

### Which components are impacted by your request?

General, UI, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adamatic-me** [comment]
I came here for the first time just to create an issue with this same request.

**Comment by danny-avila** [comment]
> I came here for the first time just to create an issue with this same request.

Awesome welcome I have plans for this but it’s not the highest in priority. It’s on my roadmap for the year

**Comment by adamatic-me** [comment]
Thanks so much @danny-avila for making LibreChat. My use case is saving money, while also sharing GPT-4 with friends and family.

This feature would help in educating my fellow users on special use cases. Right now I have to email them a list of instructions, and the various system prompts, with explanations of why this particular preset would help. I look forward to this feature when you find time for it. Thanks again!

Things that might be cool... 

- A notification badge on the presets icon when a new preset is made public on the server
- Add a description type field to presets, so that use cases can be described

**Comment by illgitthat** [comment]
Copying this over from discord in case it's helpful to anyone. Thanks @fuegovic 

> From the webUI, you can export them as json, and they can import them back, but it's a manual process. 

> https://docs.librechat.ai/features/presets.html#importingexporting-presets

![image](https://github.com/danny-avila/LibreChat/assets/2256474/32c00684-e377-423b-80f9-db4993a96c95)

**Comment by danny-avila** [comment]
After re-reading this issue, it seems that resolving https://github.com/danny-avila/LibreChat/issues/1617 would take care of the primary enhancement desired here. Closing in favor of that issue
