### ISSUE TITLE
Enhancement: support cheshire-cat-ai backend

### ISSUE THREAD

**Issue by thinker007** [danny-avila/LibreChat#2134]
### What features would you like to see added?

The Cheshire Cat is a ready-to-use AI micro-framework. Once installed and connected to a Language Model (LLM), it can be queried through APIs. These APIs return the responses provided by the LLM.

### More details

let librechat be front ui for Cheshire Cat

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Seems like this uses a unique API totally separate from anything already integrated so I won't be implementing this. Perhaps a better approach would be to allow flexibility with apps like Flowise or this, where stream of text are simply shown/recorded from a 3rd party service, rather than the involved system handling present in the app as of current iteration.
