### ISSUE TITLE
Enhancement: Fork Chat

### ISSUE THREAD

**Issue by sam1am** [danny-avila/LibreChat#2393]
### What features would you like to see added?

Please add a button to each message that allows you to "fork" the chat from that message. All previous messages before that fork point would then be added to a new chat. 

### More details

This is useful for many situations, to be able to have multiple branching chats from a chat history you just created. 

### Which components are impacted by your request?

UI

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/127555/51af9374-578c-4837-8be2-89cab358c3a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JOOKPOWER** [comment]
that's good

**Comment by danny-avila** [comment]
I love this idea and think it can be easily implemented

**Comment by danny-avila** [comment]
another approach is to only copy the visible thread, but I can maybe add an option for both

**Comment by danny-avila** [comment]
So as I dove deep into this, it turned out more complex than I'd hoped, but it has certainly been worthwhile. Merging this soon, and here's a preview of all the options

![Screenshot 2024-05-05 111824](https://github.com/danny-avila/LibreChat/assets/110412045/63baa742-1faf-4d85-bcf3-46f77d9d0ada)
![Screenshot 2024-05-04 235849](https://github.com/danny-avila/LibreChat/assets/110412045/bfdb8698-f88a-49f8-a085-c16472db60a9)
![Screenshot 2024-05-04 235903](https://github.com/danny-avila/LibreChat/assets/110412045/8b962ed5-8257-4b2a-aafd-20a8aab34bd1)
![Screenshot 2024-05-04 235913](https://github.com/danny-avila/LibreChat/assets/110412045/0c49fc32-7a6b-4e89-b120-e4c9b7d59d1a)
![Screenshot 2024-05-04 235923](https://github.com/danny-avila/LibreChat/assets/110412045/0bda10ef-d61b-40a6-98f1-590013cdcfe3)
![Screenshot 2024-05-05 000029](https://github.com/danny-avila/LibreChat/assets/110412045/ea3974cc-297e-4abe-afb5-d461d8f9ee8c)
