### ISSUE TITLE
[Bug]: Token values for claude is not correct when using OpenRouter

### ISSUE THREAD

**Issue by nayakayp** [danny-avila/LibreChat#3795]
### What happened?

When I use the Claude model claude-3.5-sonnet via the OpenRouter endpoint, the token rate is incorrect. It spends 0.8 for the prompt and 2.4 for completion. The correct values for that model are 3 for the prompt and 15 for completion.

I'm guessing there's a typo in api/models/tx.js. It defines claude-3-5-sonnet. Shouldn't it be using a dot instead of a hyphen, like this: claude-3.5-sonnet?

### Steps to Reproduce

1. Select OpenRouter
2. Select model `claude-3.5-sonnet`
3. Chatting
4. See the transactions collection via database

### What browsers are you seeing the problem on?

Chrome

### Screenshots

<img width="499" alt="image" src="https://github.com/user-attachments/assets/6d81a2fb-bf31-46c1-8b4e-e9bd68c6a370">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> I'm guessing there's a typo in api/models/tx.js. It defines claude-3-5-sonnet. Shouldn't it be using a dot instead of a hyphen, like this: claude-3.5-sonnet?

This is not a typo, from [Anthropic API docs:](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table)

![image](https://github.com/user-attachments/assets/de2ff437-53f9-4324-a7a9-10ad75922802)

That said, we can make sure to handle the naming pattern. More info on how we handle OR:

---

With Openrouter, we actually fetch the model names and pricing from their API. This what the data for 3.5 Sonnet looks like:

```js
{
  id: "anthropic/claude-3.5-sonnet",
  name: "Anthropic: Claude 3.5 Sonnet",
  created: 1718841600,
  description: "Claude 3.5 Sonnet delivers better-than-Opus capabilities, faster-than-Sonnet speeds, at the same Sonnet prices. Sonnet is particularly good at:\n\n- Coding: Autonomously writes, edits, and runs code with reasoning and troubleshooting\n- Data science: Augments human data science expertise; navigates unstructured data while using multiple tools for insights\n- Visual processing: excelling at interpreting charts, graphs, and images, accurately transcribing text to derive insights beyond just the text alone\n- Agentic tasks: exceptional tool use, making it great at agentic tasks (i.e. complex, multi-step problem solving tasks that require engaging with other systems)\n\n#multimodal",
  pricing: {
    prompt: "0.000003",
    completion: "0.000015",
    image: "0.0048",
    request: "0",
  },
  context_length: 200000,
  architecture: {
    modality: "text+image->text",
    tokenizer: "Claude",
    instruct_type: null,
  },
  top_provider: {
    context_length: 200000,
    max_completion_tokens: 8192,
    is_moderated: true,
  },
  per_request_limits: null,
}
```

For the transactions, it matches:

![image](https://github.com/user-attachments/assets/0b529ba0-8361-4ae4-a107-29fb6616ba8b)

The reason for your discrepancy is due to:
1. not fetching models
2. openrouter using `claude-3.5-sonnet` instead of the officially recognized `claude-3-5-sonnet`
