### ISSUE TITLE
[Bug]: different models are selectable, even if they are not configured

### ISSUE THREAD

**Issue by thunderbug1** [danny-avila/LibreChat#496]
### What happened?

When using the AZURE_OPENAI_API_* settings I always see the selection drop down to select different models no matter if they are configured or not.
I tried commenting out OPENAI_MODELS as well as setting it to one model name (chat) but I still get the selection drop down.
For example I can select gpt-4, even if it isn't even available in the region where the ressource is deployed.

![image](https://github.com/danny-avila/LibreChat/assets/1395321/e30631d8-76f4-4476-9990-b9387a3395a2)

Also the OpenAI endpoint is selectable even though the settings for it are commented out.

![image](https://github.com/danny-avila/LibreChat/assets/1395321/29f4dd0f-f8bd-467c-94e6-55c0f6594ffe)

### Steps to Reproduce

1. Set values in .env file for:
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_API_INSTANCE_NAME=
AZURE_OPENAI_API_DEPLOYMENT_NAME=
AZURE_OPENAI_API_VERSION=2023-03-15-preview
AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME=
AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=

2. comment out all ChatGPT Endpoint settings
3. Start with docker-compose up
4. open librechat page

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thunderbug1** [comment]
comment: interestingly the chat only works when the OPENAI endpoint is selected. 
When I select the "Azure OpenAI" endpoint it does not work anymore even though the Azure endpoint is the only one configured.

**Comment by danny-avila** [comment]
You need to set the OPENAI_MODELS to what they should be, instead of commenting them out:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/13895450-826f-4c91-90f3-01d8d67af1c4)

`OPENAI_MODELS=gpt-3.5-turbo`


The azureOpenAI setting as an endpoint should be removed or developed differently. It was developed by Wentao who had access and had most of the functionality for it on his fork. I'm surprised to see you have it, were you using his fork?


That said, seeing the OpenAI endpoint is expected, the azure open AI endpoint is not expected.

**Comment by thunderbug1** [comment]
no I am using the main branch, no fork.

I figured it out, the config line for OPENAI_MODELS in the .env file must not contain any comments after the list. Even if VS code shows it as as a Comment it somehow messes with how it is read.
