### ISSUE TITLE
[Request]: azureOpenAI API as its own endpoint

### ISSUE THREAD

**Issue by jinzishuai** [danny-avila/LibreChat#548]
### What happened?

From both UI and the `.env.example` file, I see options to configure the Azure OpenAI. However, when I used it, I got the following error
![image](https://github.com/danny-avila/LibreChat/assets/1074685/05069a9d-2903-4d77-8fdb-f22a77d0b31e)

I then searched the API code and I didn't see the `azureOpenAI` endpoint being implemented at all. 

### Steps to Reproduce

Two ways
1. configure `.env` to include settings for Azure OpenAI in https://github.com/danny-avila/LibreChat/blob/main/.env.example#L52
2. configure OpenAI to use Azure OpenAI
![image](https://github.com/danny-avila/LibreChat/assets/1074685/6dd92d2d-8724-4b10-9de3-b9ab1b5d9f15)

Either way won't work.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is because a past contributor made that endpoint on his own fork but never contributed it here yet left some artifact of it.

Currently, Azure OpenAI will work by overriding the OpenAI endpoint, so if you have all the credentials set, you can use it in place of the regular OpenAI API.

It's on the list but I will leave this as an open issue until it's resolved. I'm working on refactoring the API client classes and it will be really easy to integrate it as an endpoint once I do.

**Comment by danny-avila** [comment]
This is now resolved by https://github.com/danny-avila/LibreChat/pull/532

See this link for fully setting up the Azure endpoint: https://docs.librechat.ai/features/azure.html
