### ISSUE TITLE
enhancement: Add Proxy to Langchain Calls

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/LibreChat#642]
### What happened?

seems to use `configuration.baseOptions` in `ChatOpenAI({ credentials, configuration, ...modelOptions }, configOptions);`

It's defined in [here](https://github.com/openai/openai-node/blob/master/configuration.ts#L77)
and we can set any axios configs.

in Axios configuration, there is 
```

  proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  },
```
can be used.

### Steps to Reproduce

in somewhere needs proxy

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I'd made a small mistake where the reverse proxy url would not be set for langchain. 

In the current implementation, for a reverse Proxy url, it must mirror OpenAI API endpoints to be used in a similar manner for OpenAI without plugins, the URL starting with v1. 

Example: 
`OPENAI_REVERSE_PROXY=http://localhost:8080/v1/chat/completions`

For setting the proxy as you said, this is still to do but should be simple. I'm looking at this https://github.com/hwchase17/langchainjs/issues/1925

Would be in the PluginsClient file, where I'm already handling base options with configOptions

**Comment by wtlyu** [comment]
I have used this line in langchain to get proxy work in my another project.

However, it's python

```
OPENAI_ARGV = {'openai_api_key': settings.OPENAI_API_KEY, 'openai_proxy': settings.OPENAI_PROXY}
```

works for OpenAI and ChatOpenAI

**Comment by danny-avila** [comment]
@Manouchehri documenting possible solutions here:

https://github.com/langchain-ai/langchainjs/issues/2339#issuecomment-1706262462
https://github.com/langchain-ai/langchainjs/issues/1454#issuecomment-1573434503


Note that streaming with forward proxy won't work (not a dealbreaker since I don't rely on langchain streaming from OpenAI, but good thing to note):
https://github.com/langchain-ai/langchainjs/issues/1925#issuecomment-1683912775
