### ISSUE TITLE
[Bug]: ChatOpenAI Client Defaults to Azure OpenAI for plugins.

### ISSUE THREAD

**Issue by Falven** [danny-avila/LibreChat#827]
### What happened?

In 0.5.4, if using both `Azure OpenAI` and the `OpenAI` plugins with a `user-provided` or key defined as an environment variable, ChatOpenAI will default to using the Azure OpenAI endpoint and the OpenAI plugins won't work. We need to see how we can manage the environment variables when creating the client so that we can support hybrid scenarios.

### Steps to Reproduce

1. Set up Azure OpenAI Keys:
```ts
process.env.AZURE_OPENAI_API_KEY;
process.env.AZURE_OPENAI_API_INSTANCE_NAME;
process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
process.env.AZURE_OPENAI_API_VERSION;
```
2. Set up an `OPENAI_API_KEY`:
```ts
process.env.OPENAI_API_KEY
```
3. Observe that requests will go to Azure OpenAI even if a user-provided OPENAI_API_KEY is available in the environment variables.
4. Now delete the Azure OpenAI environment variables right before creating the ChatOpenAI Client:
`PluginsClient.js:175`
```ts
delete process.env.AZURE_OPENAI_API_KEY;
delete process.env.AZURE_OPENAI_API_INSTANCE_NAME;
delete process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
delete process.env.AZURE_OPENAI_API_VERSION;
```
And watch the plugins work when using a valid key.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
As of 0.5.3, I addressed this issue with the following

>Changed AZURE_OPENAI_API_KEY to AZURE_API_KEY:
I had to change the environment variable from AZURE_OPENAI_API_KEY to AZURE_API_KEY, because the former would be read by langchain and cause issues when a user has both Azure and OpenAI keys set. This is a **[known issue in the langchain library](https://github.com/hwchase17/langchainjs/issues/1687)**

https://docs.librechat.ai/general_info/breaking_changes.html#v054

Let me know if this addresses the issue.

**Comment by danny-avila** [comment]
I do think the env. variable handling is a bit tricky and some work needs to be done to handle using plugins dynamically, with or without env variables set. As of now, you will also need to explicitly define `PLUGINS_USE_AZURE=true` as well.

This should be a quick fix to update this behavior
