### ISSUE TITLE
Enhancement: Can you Add Bard Cookies as Well

### ISSUE THREAD

**Issue by darnells68** [danny-avila/LibreChat#833]
### Contact Details

fusionfalls689@gmail.com

### What features would you like to see added?

I see we already have Palm2 but similarly to how we have bing and can access the bingchat bot, Can we use the cookies from bard to access bard. The same I'd ask about antropic using the cookies to access the LLM. Also Bing added a captcha to chat which sometimes breaks the bing feature please allow us the ability to see the captcha so we can solve it 

### More details

I see we already have Palm2 but similarly to how we have bing and can access the bingchat bot, Can we use the cookies from bard to access bard. The same I'd ask about antropic using the cookies to access the LLM. Also Bing added a captcha to chat which sometimes breaks the bing feature please allow us the ability to see the captcha so we can solve it 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I won’t be adding Bard or Anthropic via browser hacks, Bing is already enough trouble. It’s a cat and mouse game and I can’t reproduce a lot of errors people have based on IP/overuse.

official API are welcome which is why I added Anthropic.

In any case, the CAPTCHA can be circumvented by manually visiting the site, you can check our discord to overcome this and more obstacles with bing, and it’s not an easy thing to hack it into LibreChat. I already use a 3rd party package for bing so edits to the library will rely on another maintainer and I’d rather not spend time developing on this.
